"""create users and tracked_products tables

Revision ID: beb1dfb0ae5f
Revises: 1d74b24dcbfb
Create Date: 2026-01-12 16:57:22.582525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb1dfb0ae5f'
down_revision: Union[str, Sequence[str], None] = '1d74b24dcbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
